### ISSUE TITLE
[Header] - 사파리에서 laptop -> mobile로 줄일 시 header가 3개가 되는현상

### ISSUE THREAD

**Issue by jinn2u** [selab-hs/selab-core-web#29]
## 📑 작업 사항 
사파리에서 laptop -> mobile로 줄일 시 header가 3개가 되는 현상 수정하기

https://user-images.githubusercontent.com/70435257/163081481-abfeb961-9a83-43b5-a607-ab0a8527f327.mp4

**Comment by minbr0ther** [comment]
✅ float: rigtht -> position: absolute로 해결
